### ISSUE TITLE
Formatting error

### ISSUE THREAD

**Issue by LouisCAD** [googlesamples/android-codelab-watchface#1]
Hi!
I found a formatting error at the second bullet in the **Account for the peek card in ambient mode** heading of [4th step](https://www.code-labs.io/codelabs/android-wear-watchface/index.html?index=..%2F..%2Findex#3).

**Comment by keyboardsurfer** [comment]
Hi @LouisCAD, thanks for the report. We're looking into this.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there. In addition, the new location can accept Pull Requests (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
