### ISSUE TITLE
The remaining time is always 0min

### ISSUE THREAD

**Issue by LouisCAD** [googlesamples/android-codelab-watchface#2]
![screen shot 2015-12-03 at 08 09 25](https://cloud.githubusercontent.com/assets/6975237/11554088/43f769f4-9995-11e5-8b00-513d6f89b8a2.png)

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there. In addition, the new location can accept Pull Requests (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
