### ISSUE TITLE
Incompatibility with Android Studio 3.6

### ISSUE THREAD

**Issue by DrN3RD** [googlesamples/android-codelab-watchface#4]
Is it possible to update the tutorial so that it complies with the latest dependencies, and nomenclature. 

I am getting an amazing amount of errors on build.

Your guide is awesome. But I cant follow it :(

**Comment by benoitdevos** [comment]
+1 for updating this tutorial with latest dependencies.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there. In addition, the new location can accept Pull Requests (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
